!23456789---------------------------------------------------------------!
            Program MycreateFF
               implicit none
               integer i,j,k,l,Na,Nt,flag,num,pairmax,i1,j1,fun,bondmax
               integer anglemax,dihmax,mul,impromax,fp
               parameter (Na=11921) !no of atoms
               double precision mass,charge,sigma,epsil,bo,kb
               double precision theta,ktheta,r13,kub,phi,kphi,zeta,kzeta
               character*6 nami,namj,namk,naml,atomt(Na) !maxsize Na
               character*6 atom1,atom2,atom3,atom4
               character*1  ptype
               character*32 filename
!===============================================================
          open(32,file='outputs/forcefield.itp',status='unknown') 
          !----------maxrows----------------------!
           filename= 'atomtypes.dat'
           call findmaxrows(filename,Nt)
           filename= 'bondtypes.dat'
           call findmaxrows(filename,bondmax)
           filename= 'pairtypes.dat'
           call findmaxrows(filename,pairmax)
           filename= 'angletypes.dat'
           call findmaxrows(filename,anglemax)
           filename= 'dihedraltypes.dat'
           call findmaxrows(filename,dihmax)
           filename= 'impropertypes.dat'
           call findmaxrows(filename,impromax)
  
          !-----------WELCOME----------------------!
           write(32,'(a)') ';;'
           write(32,'(a)') ';; Charmm FF generated by Rakesh Vaiwala'
           write(32,'(5a)') ';;',new_line(''),';;', new_line(''),';;'
           write(32,'(a)') ';; Corresponance:'
           write(32,'(a)') ';; multiscalesimu@gmail.com'
           write(32,'(a)') ';;'
           write(32,'(a)') ';; Charmm36 FF in GROMACS format'
           write(32,'(a)') ';;'  
           
          !-----------[ defaults ] -----------------!
           write(32,'(a)') ''
           write(32,'(a)') '[ defaults ]'
           write(32,'(a)') ';nbfunc comb-rule gen-pairs fudgeLJ fudgeQQ'
           write(32,'(i1,i6,a12,2F8.1)') 1, 2, 'yes', 1.0, 1.0
          !-----------atomtypes----------------------!  
           open(11,file='inputs/atomtypes.dat')
           write(32,'(a)') ''
           write(32,'(a)') ''
           write(32,'(a)') '[ atomtypes ]'
           write(32,'(a)') ';name  at.num  mass charge  ptype  sigma(nm)
     +        espilon(kJ/mol)'     
             do i=1,Nt
              read(11,*) atomt(i)
              open(52,file='charmm36Databank/atomtypes.itp',
     +          status='old')
              flag = 0
             do while(flag .eq. 0)
              read(52,*) nami, num, mass, charge, ptype, sigma, epsil  
              if(nami .eq. atomt(i)) then
                 flag = 1
               !   write(*,*) nami, num, mass, charge, ptype,sigma,epsil
        write(32,'(a8,i6,F11.4,F11.3,a6,ES21.11,ES16.6)') adjustr(nami),
     +                 num,mass,charge, ptype,sigma,epsil
              endif
              enddo
              close(52)
            enddo
            !--------TIP3P water---------!
        write(32,'(a8,i6,F11.4,F11.3,a6,ES21.11,ES16.6)') adjustr('OT'),
     +            8,15.9994,-0.834, ptype,3.15057422683d-1,6.363864d-1
        write(32,'(a8,i6,F11.4,F11.3,a6,ES21.11,ES16.6)') adjustr('HT'),
     +            1,1.0080,0.417, ptype,4.00013524445d-2,1.924640d-1
            !-----------IONS--------------!
        write(32,'(a8,i6,F11.4,F11.3,a6,ES21.11,ES16.6)')adjustr('POT'),
     +            19,39.0983,1.000,ptype,3.14264522824d-1,3.640100d-1
        write(32,'(a8,i6,F11.4,F11.3,a6,ES21.11,ES16.6)')adjustr('SOD'),
     +            11,22.98977,1.000,ptype,2.51367073323d-1,1.962300d-1
        write(32,'(a8,i6,F11.4,F11.3,a6,ES21.11,ES16.6)')adjustr('CLA'),
     +            17,35.45,-1.000,ptype,4.04468018036d-1,6.276d-1

          !------------pairtypes---------------------!
          open(13,file='inputs/pairtypes.dat')
          write(32,'(a)') ''
          write(32,'(a)') '[ pairtypes ]'
          write(32,'(a)') ';i  j   func sigma1-4(nm) epsilon1-4(kJ/mol)'
           do k=1,pairmax
               read(13,*) atom1,atom2
               open(52,file='charmm36Databank/pairtypes.itp',
     +          status='old')
                flag=0
              do 
                 read(52,*,end=100) nami, namj, fun, sigma, epsil
               if(((nami .eq. atom1).and.(namj .eq. atom2)) .or.
     +           ((nami .eq. atom2).and.(namj .eq. atom1)) ) then
                 flag = 1
          write(32,'(a7,a8,i6,2ES19.11)') adjustr(atom1),
     +           adjustr(atom2),fun,sigma,epsil
                exit
               endif
              enddo
 100         close(52)
            enddo
          !--------------bondtypes------------------!
          open(14,file='inputs/bondtypes.dat')
          write(32,'(a)') ''
          write(32,'(a)') '[ bondtypes ]'
          write(32,'(a)') ';i   j    func    b0(nm)    Kb(kJ/mol nm2)'
           do k=1,bondmax
               read(14,*) atom1,atom2
               open(52,file='charmm36Databank/bondtypes.itp',
     +          status='old')
                flag=0
              do while(flag .eq. 0)
                 read(52,*) nami, namj, fun, bo, kb
              if(((nami .eq. atom1).and.(namj .eq. atom2)) .or.
     +           ((nami .eq. atom2).and.(namj .eq. atom1)) ) then
                 flag = 1
          write(32,'(a7,a8,i6,2ES14.6)') adjustr(atom1),
     +           adjustr(atom2),fun,bo,kb
              endif
              enddo
              close(52)
            enddo
          !------------TIP3 water--------------!
          write(32,'(a7,a8,i6,2ES14.6)') adjustr('HT'),
     +           adjustr('HT'),1,1.513900d-1,0.d0
          write(32,'(a7,a8,i6,2ES14.6)') adjustr('HT'),
     +           adjustr('OT'),1,9.572000d-2,3.765600d5
  
          !---------------angletypes---------------------!
           open(15,file='inputs/angletypes.dat')
           write(32,'(a)') ''
           write(32,'(a)') '[ angletypes ]'
           write(32,'(a)') ';i    j    k     func    theta(degree)
     + ktheta(kJ/mol rad2)  r13(nm)   kub(kJ/mol nm2)' 
         do k=1,anglemax
               read(15,*) atom1,atom2,atom3
               open(52,file='charmm36Databank/angletypes.itp',
     +          status='old')
                flag=0
           do while(flag.eq.0)
                 read(52,*) nami, namj, namk, fun,theta,ktheta, r13,kub
          if(((nami.eq.atom1).and.(namj.eq.atom2).and.(namk.eq.atom3))
     +   .or.((nami.eq.atom3).and.(namj.eq.atom2).and.(namk.eq.atom1)))
     +    then
                 flag = 1
          write(32,'(a7,2a8,i6,4ES15.7)') 
     +        adjustr(atom1),adjustr(atom2),adjustr(atom3),fun,
     +        theta,ktheta,r13,kub
              endif
              enddo
              close(52)
            enddo
          !-----------TIP3 water----------------!
          write(32,'(a7,2a8,i6,4ES15.7)')
     +        adjustr('HT'),adjustr('OT'),adjustr('HT'),5,
     +        1.0452d2,4.60240d2,0.d0,0.d0

           !------------proper-dihedrals----------------!
            open(16,file='inputs/dihedraltypes.dat')
            write(32,'(a)') ''
            write(32,'(a)') '[ dihedraltypes ]'
            write(32,'(a)') ';i    j     k     l     func   phi(degree)
     +       kphi(kJ/mol)     mul'
         do k=1,dihmax
               read(16,*) atom1,atom2,atom3,atom4
               open(52,file='charmm36Databank/dihedraltypes.itp',
     +          status='old')
                flag=0
           do while(flag.eq.0)
                read(52,*) nami, namj, namk,naml,fun,phi,kphi,mul
                if(( (nami.eq.atom1).and.(namj.eq.atom2).and.
     +               (namk.eq.atom3).and.(naml.eq.atom4)     ).or.
     +             ( (nami.eq.atom4).and.(namj.eq.atom3).and.
     +               (namk.eq.atom2).and.(naml.eq.atom1)  ) )then  
                     flag = 1
                write(32,'(a7,3a8,i6,2ES14.6,i6)')
     +          adjustr(atom1),adjustr(atom2),adjustr(atom3),
     +          adjustr(atom4), fun,phi,kphi,mul
                   do j=2,3  !checking for multiple potentials
                    read(52,*) nami,namj,namk,naml,fun,phi,kphi,mul
                    if(( (nami.eq.atom1).and.(namj.eq.atom2).and.
     +                   (namk.eq.atom3).and.(naml.eq.atom4)     ).or.
     +                 ( (nami.eq.atom4).and.(namj.eq.atom3).and.
     +                   (namk.eq.atom2).and.(naml.eq.atom1)  ) )then 
                write(32,'(a7,3a8,i6,2ES14.6,i6)')
     +          adjustr(atom1),adjustr(atom2),adjustr(atom3),
     +          adjustr(atom4), fun,phi,kphi,mul
                    else
                       exit  
                    endif
                   enddo
                elseif(nami.eq.'X'.and.naml.eq.'X')then
                   if( ((namj.eq.atom2).and.(namk.eq.atom3)).or.
     +                 ((namj.eq.atom3).and.(namk.eq.atom2)) )then
                     flag = 1
                write(32,'(a7,3a8,i6,2ES14.6,i6)')
     +          adjustr(atom1),adjustr(atom2),adjustr(atom3),
     +          adjustr(atom4), fun,phi,kphi,mul
                   endif
                endif
              enddo
              close(52)
             enddo
         !--------------improper-dihedrals-----------------!
           open(17,file='inputs/impropertypes.dat')
           write(32,'(a)') ''
           write(32,'(a)') '[ dihedraltypes ]'  
           write(32,'(a)') ';i      j     k    l    func   zeta(degree)
     +     kzeta(kJ/mol rad2)'

         do k=1,impromax
               read(17,*) atom1,atom2,atom3,atom4
               open(52,file='charmm36Databank/impropertypes.itp',
     +          status='old')
                flag=0
           do while(flag.eq.0)
                 read(52,*) nami, namj, namk,naml,fun,zeta,kzeta
                 if(( (nami.eq.atom1).and.(namj.eq.atom2).and.
     +                (namk.eq.atom3).and.(naml.eq.atom4)     ).or.
     +              ( (nami.eq.atom4).and.(namj.eq.atom3).and.
     +                (namk.eq.atom2).and.(naml.eq.atom1)  ) )then 
                 flag = 1
              write(32,'(a7,3a8,i6,2ES14.6)')
     +        adjustr(atom1),adjustr(atom2),adjustr(atom3),
     +        adjustr(atom4), fun,zeta,kzeta
              endif
              enddo
              close(52)
             enddo
              !-------include---cmap-------!
              write(32,'(a)') ''
              write(32,'(a)') '#include "cmap.itp"'
              !------------------------------------------------------!
              close(11)
              close(13)
              close(14)
              close(15)
              close(16)
              close(17)
              close(32)
             END
!=======================================================================!
             include 'findmaxrows.f'  
