            !-----------WELCOME----------------------!
          write(32,'(a)')  ';;'
          write(32,'(a)')  ';; Generated by Rakesh Vaiwala'
          write(32,'(5a)') ';;',new_line(''),';;',new_line(''),';;'
          write(32,'(a)')  ';; Corresponance:'
          write(32,'(a)')  ';; multiscalesimu@gmail.com'
          write(32,'(a)')  ';;'
          write(32,'(2a)')  ';; GROMACS topology:',molname
          write(32,'(a)')  ';;'

          !-----------[ moleculetype ] -----------------!
          write(32,'(a)') ''
          write(32,'(a)') ''
          write(32,'(a)') '[ moleculetype ]'
          write(32,'(a)') '; name  nrexcl'
          write(32,'(a6,i4)') molname,  3
          !-----------[ atoms ]-------------------------!
          write(32,'(a)') ''
          write(32,'(a)') '[ atoms ]'
          write(32,'(a)') ';nr type resnr residue atom cgnr charge mass'
!-----------------------------------
